version: '3.8'
services:
  app:
    env_file:
      - base.env
      - svc-a.env
    environment:
      FOO: bar
      FIZZ: "buzz"
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "${SVC_A_HOST_PORT}:9090"
